openni:
    build: openni/.
    privileged: true
    volumes:
        - "/dev/bus/usb"
    links:
        - "master"
    environment:
        # - "ROS_HOSTNAME=172.17.0.34"
        - "ROS_MASTER_URI=http://master:11311"
    command: "'source /opt/ros/indigo/setup.bash && sleep 1 && roslaunch openni_launch openni.launch'"
    # command: "'ping master'"

master:
    build: master/.
    # command: "'source /opt/ros/indigo/setup.bash && roscore'"
    # command: "'ping 8.8.8.8 > /dev/null'"
